### ISSUE TITLE
DWConnector Spark 3.4 documentation.

### ISSUE THREAD

**Issue by chelyabinsk** [microsoft/synapse-spark-runtime#2]
Hello @SparkVHDReleaseManagementTeam,

I can't help but notice that for [Synapse Spark 3.2](https://github.com/microsoft/synapse-spark-runtime/blob/876e6102a93c19877cc3d551816d8c2bf6da4a0c/Synapse/spark3.2/Official-Spark3.2-Rel-2024-05-10.0-rc.1.md?plain=1#L27) `DWConnector` is at version `2.1.1`, for [Synapse Spark 3.3](https://github.com/microsoft/synapse-spark-runtime/blob/876e6102a93c19877cc3d551816d8c2bf6da4a0c/Synapse/spark3.3/Official-Spark3.3-Rel-2024-04-18.3-rc.1.md?plain=1#L47)  version becomes `2.1.1 --> 2.1.2`, but for [Synapse Spark 3.4](https://github.com/microsoft/synapse-spark-runtime/blob/876e6102a93c19877cc3d551816d8c2bf6da4a0c/Synapse/spark3.4/Official-Spark3.4-Rel-2024-03-27.2-rc.1.md?plain=1#L57) `DWConnector` has version `1.0.0`. Is this correct? We are in the middle of migration from 3.2 to 3.4 and rely quite heavily on `DWConnector`, and this seems like a major downgrade. Is there a document that highlights the changes to the `DWConnector` by releases?

I checked related documents in the Fabric folder, and similar pattern is present there as well.

[Fabric Spark 3.3](https://github.com/microsoft/synapse-spark-runtime/blob/876e6102a93c19877cc3d551816d8c2bf6da4a0c/Fabric/spark3.3/Official-Spark3.3-Rel-2024-05-01.3-rc.1.md?plain=1#L42) `2.1.1 --> 2.1.3`
[Fabric Spark 3.4](https://github.com/microsoft/synapse-spark-runtime/blob/876e6102a93c19877cc3d551816d8c2bf6da4a0c/Fabric/spark3.4/Official-Spark3.4-Rel-2024-04-18.4-rc.1.md?plain=1#L45) `1.0.0`
[Fabric Spark 3.5](https://github.com/microsoft/synapse-spark-runtime/blob/876e6102a93c19877cc3d551816d8c2bf6da4a0c/Fabric/spark3.5/Official-Spark3.5-Rel-2024-05-08.2-rc.1.md?plain=1#L17) `1.0.0`

Thank you for your assistance

**Comment by ekote** [comment]
@jomoyer121

**Comment by SparkVHDReleaseManagementTeam** [comment]
The component 'DWConnector' tracks versioning separately at the component level for each Spark version.  They're not comparable between spark versions as the changes are tracked separately (so Spark 3.5 version 1.0.0 might be the same implementation as Spark 3.3 version 2.0.0)

The underlying libraries included in the component are tracked separately as part of the release notes, and of these you're largely concerned with the sqlanalyticsconnector/sqlanalyticsconnector-fabric - but these are also largely governed by separate branches for the various spark versions as well (and were started back at 1.0.0 for Mariner based VHDs, hence the significant different with newer Spark Versions **(there is no actual downgrade)**.

Libraries:

- sqlanalyticsconnectorpy
- sqlanalyticsconnector
- sqlanalyticsconnector-fabric
- config (java/scala)
- mssql-jdbc

Recent versions:
Synapse:
- 3.2 - mssql-jdbc 8.4.1.jre8; sqlanalyticsconnectorpy 1.0.1; sqlanalyticsconnector 3.2.0-2.1.2; config 1.3.4
- 3.3 - mssql-jdbc 8.4.1.jre8; sqlanalyticsconnectorpy 1.0.1; sqlanalyticsconnector 3.3.0-2.1.3; config 1.3.4
- 3.4 - mssql-jdbc 8.4.1.jre8; sqlanalyticsconnectorpy 1.0.1; sqlanalyticsconnector 3.4.0-1.0.2; config 1.3.4

Fabric
- 3.3 - mssql-jdbc 8.4.1.jre8; sqlanalyticsconnectorpy 1.0.1; sqlanalyticsconnector-fabric 3.3.0-1.0.4; config 1.3.4
- 3.4 - mssql-jdbc 8.4.1.jre8; sqlanalyticsconnectorpy 1.0.1; sqlanalyticsconnector-fabric 3.4.1-1.0.2; config 1.3.4
- 3.5 - mssql-jdbc 8.4.1.jre8; sqlanalyticsconnectorpy 1.0.1; sqlanalyticsconnector-fabric 3.4.1-1.0.0; config 1.3.4

We'll try to adjust the versioning and presentation of component versions to make this a little more clear for the end users.

**Comment by chelyabinsk** [comment]
This now answers my question. Much appreciated. Closing.
